# Generated by Django 6.0.6 on 2026-07-27 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GAD7Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')])),
                ('q2', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')])),
                ('q3', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')])),
                ('q4', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')])),
                ('q5', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')])),
                ('q6', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')])),
                ('q7', models.PositiveSmallIntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')])),
                ('difficulty', models.CharField(blank=True, choices=[('not', 'Not difficult at all'), ('somewhat', 'Somewhat difficult'), ('very', 'Very difficult'), ('extremely', 'Extremely difficult')], max_length=20)),
                ('total_score', models.PositiveSmallIntegerField(default=0)),
                ('interpretation', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GAD-7 Assessment',
                'verbose_name_plural': 'GAD-7 Assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
