# Generated by Django 6.0.6 on 2026-07-27 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_gad7assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StressAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.PositiveSmallIntegerField()),
                ('q2', models.PositiveSmallIntegerField()),
                ('q3', models.PositiveSmallIntegerField()),
                ('q4', models.PositiveSmallIntegerField()),
                ('q5', models.PositiveSmallIntegerField()),
                ('q6', models.PositiveSmallIntegerField()),
                ('q7', models.PositiveSmallIntegerField()),
                ('q8', models.PositiveSmallIntegerField()),
                ('q9', models.PositiveSmallIntegerField()),
                ('q10', models.PositiveSmallIntegerField()),
                ('total_score', models.PositiveSmallIntegerField(default=0)),
                ('interpretation', models.CharField(blank=True, choices=[('Minimal Stress', 'Minimal Stress'), ('Mild Stress', 'Mild Stress'), ('Moderate Stress', 'Moderate Stress'), ('High Stress', 'High Stress')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stress Assessment',
                'verbose_name_plural': 'Stress Assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
