# Generated by Django 6.0.6 on 2026-06-29 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_services_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='services',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='short_description',
            field=models.CharField(default='Professional counselling service.', max_length=200),
        ),
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='services/'),
        ),
    ]
