# Generated by Django 6.0.6 on 2026-06-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_services_options_services_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.URLField(),
        ),
    ]
