# Generated by Django 6.0.6 on 2026-08-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounsellorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=255)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="counsellors/"),
                ),
                ("bio", models.TextField()),
                (
                    "specializations",
                    models.TextField(help_text="Enter one specialization per line."),
                ),
                ("experience", models.TextField()),
                (
                    "qualifications",
                    models.TextField(help_text="Enter one qualification per line."),
                ),
                ("approach", models.TextField()),
                ("years_experience", models.PositiveIntegerField(default=0)),
                ("online_support", models.BooleanField(default=True)),
                ("in_person_support", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Counsellor Profile",
                "verbose_name_plural": "Counsellor Profile",
            },
        ),
    ]
