# Generated by Django 6.0.6 on 2026-08-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselors", "0002_counsellorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="counsellorprofile",
            name="short_bio",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Short introduction displayed on the homepage.",
            ),
        ),
        migrations.AlterField(
            model_name="counsellorprofile",
            name="bio",
            field=models.TextField(
                help_text="Full biography displayed on the About Us page."
            ),
        ),
    ]
