# Generated by Django 6.0.6 on 2026-07-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientprofile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='avatar',
            new_name='profile_photo',
        ),
    ]
