# Generated by Django 6.0.6 on 2026-08-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="session_mode",
            field=models.CharField(
                choices=[("online", "Online"), ("physical", "In Person")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual Therapy"),
                    ("couples", "Couples Therapy"),
                    ("family", "Family Therapy"),
                    ("group", "Group Therapy"),
                    ("corporate", "Corporate Therapy"),
                ],
                max_length=30,
            ),
        ),
    ]
