# Generated by Django 6.0.6 on 2026-08-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0007_alter_session_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
