# Generated by Django 6.0.6 on 2026-08-27 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0008_delete_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking",
                to="appointments.session",
            ),
        ),
    ]
